# FX Market Risk Pipeline - Base Configuration
# This file contains environment-agnostic settings shared across dev/prod

# Pipeline Metadata
pipeline:
  name: fx_market_risk
  version: "1.0.0"
  timezone: Europe/Madrid
  description: "FX Market Risk VaR Calculation Pipeline"

# Currency Pairs Configuration
currencies:
  pairs:
    - symbol: EURUSD
      name: EUR/USD
      base_currency: EUR
      quote_currency: USD
      liquidity_tier: tier1
      base_position_size: 15000000  # $15M
      is_usd_quote: true

    - symbol: GBPUSD
      name: GBP/USD
      base_currency: GBP
      quote_currency: USD
      liquidity_tier: tier1
      base_position_size: 8000000   # $8M
      is_usd_quote: true

    - symbol: USDJPY
      name: USD/JPY
      base_currency: USD
      quote_currency: JPY
      liquidity_tier: tier1
      base_position_size: 10000000  # $10M
      is_usd_quote: false

    - symbol: USDCHF
      name: USD/CHF
      base_currency: USD
      quote_currency: CHF
      liquidity_tier: tier2
      base_position_size: 5000000   # $5M
      is_usd_quote: false

    - symbol: USDBRL
      name: USD/BRL
      base_currency: USD
      quote_currency: BRL
      liquidity_tier: tier3
      base_position_size: 3000000   # $3M
      is_usd_quote: false

# VaR (Value at Risk) Calculation Parameters
var_parameters:
  confidence_level: 0.95            # 95% confidence interval
  percentile_long: 0.05             # 5th percentile for LONG positions (downside risk)
  percentile_short: 0.95            # 95th percentile for SHORT positions (upside risk)
  lookback_days: 30                 # Rolling window for VaR calculation
  lookback_interval_days: 35        # Data fetch interval (lookback + buffer)
  minimum_data_date: "2025-01-01"   # Filter out positions before this date
  return_anomaly_threshold: 0.15    # Flag returns > 15% as anomalies

# Position Generation Parameters (for simulation/testing)
position_generation:
  desk: "FX Spot Desk"
  direction_bias:
    long_probability: 0.70          # 70% chance of LONG position
    short_probability: 0.30         # 30% chance of SHORT position
  flat_probability: 0.05            # 5% chance of FLAT (no position)
  random_walk:
    max_deviation: 0.20             # ±20% variation from base position size

# Data Quality & Validation
data_validation:
  fx_rates:
    required_fields:
      - ticker
      - results
    max_records_per_day: 1000

  positions:
    required_fields:
      - currency_pair
      - position_size
      - direction
    allowed_directions:
      - LONG
      - SHORT
      - FLAT

# External API Configuration
api:
  polygon:
    base_url: "https://api.polygon.io"
    endpoint_template: "/v2/aggs/ticker/C:{currency_pair}/range/1/day/{start_date}/{end_date}"
    timeout_seconds: 30
    retry_attempts: 3
    secret_scope: guidotognini
    secret_key: polygon_api_key

# Delta Lake Table Properties
table_properties:
  auto_optimize_write: true
  auto_compact: true
  schema_evolution_mode: rescue

# Medallion Architecture Layer Names
layers:
  bronze:
    fx_rates: bronze_fx_daily_rates
    positions: bronze_daily_positions
  silver:
    fx_rates: silver_fx_daily_rates
    fx_rates_staging: silver_fx_daily_rates_staging
    fx_returns: silver_fx_daily_returns
    positions: silver_daily_positions
  gold:
    var: gold_fct_var
